#augument the data

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
import cv2
from os import listdir
import time   

In [ ]:
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return f"{h}:{m}:{round(s,1)}"

In [ ]:
def augment_data(file_dir, n_generated_samples, save_to_dir):
    data_gen = ImageDataGenerator(rotation_range=30, 
                                  width_shift_range=0.1,
                                  height_shift_range=0.15, 
                                  shear_range=0.25, 
                                  zoom_range = 0.2,
                                  horizontal_flip=True, 
                                  vertical_flip=False, 
                                  fill_mode='nearest',
                                  brightness_range=(0.5,1.2)
                                 )

    
    for filename in listdir(file_dir):
        image = cv2.imread(file_dir + '/' + filename)
        image = image.reshape((1,)+image.shape)
        save_prefix = 'aug_' + filename[:-4]    
        i=0
        for batch in data_gen.flow(x=image, batch_size=1, save_to_dir=save_to_dir,
                                   save_prefix=save_prefix, save_format='jpg'):
            i += 1
            if i > n_generated_samples:
                break

In [ ]:
start_time = time.time()

augmented_data_path = '/content/drive/MyDrive/Digital Naturalist Dataset'
augment_data(file_dir='/content/drive/MyDrive/Digital Naturalist Dataset/Bird/Great Indian Bustard Bird'
augment_data(file_dir='/content/drive/MyDrive/Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird', n_generated_samples=8, save_to_dir=augmented_data_path+'/Bird/Spoon Billed Sandpiper Bird')
augment_data(file_dir='/content/drive/MyDrive/Digital Naturalist Dataset/Flower/Corpse Flower', n_generated_samples=8, save_to_dir=augmented_data_path+'/Flower/Corpse Flower')
augment_data(file_dir='/content/drive/MyDrive/Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower', n_generated_samples=8, save_to_dir=augmented_data_path+'/Flower/Lady Slipper Orchid Flower')
augment_data(file_dir='/content/drive/MyDrive/Digital Naturalist Dataset/Mammal/Pangolin Mammal', n_generated_samples=8, save_to_dir=augmented_data_path+'/Mammal/Pangolin Mammal')
augment_data(file_dir='/content/drive/MyDrive/Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal', n_generated_samples=8, save_to_dir=augmented_data_path+'/Mammal/Senenca White Deer Mammal')


SyntaxError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
end_time = time.time()
execution_time = (end_time - start_time)
print("Elapsed Time : "+str(execution_time))

Elapsed Time : 120.47507691383362


#loading data and preprocessing

In [ ]:
#Importing Libraries

#Locating and loading datasets
import pathlib
from pathlib import Path
import os, gc, glob, random
from PIL import Image

#DataManagement and matrix calculations
import pandas as pd
import numpy as np

#Model Building
import tensorflow as tf
import keras 
import keras.backend as K
from keras.optimizers import SGD, Adam, Adagrad, RMSprop
from keras.applications import *
from keras.preprocessing import *
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Activation, BatchNormalization,Dropout
from keras.models import Model
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split

# Data Visualization
import matplotlib.pyplot as plt

#Loading and testing models
from keras.models import load_model
from keras.models import model_from_json

# Directory operations
import os
from os import listdir

#define required function

In [ ]:
def generateListofFiles(dirName):
    """This function returns a list with exact paths of files inside the given directory """
    listOfFile = os.listdir(dirName)
    allFiles = list()
    for fol_name in listOfFile:
        fullPath = os.path.join(dirName, fol_name)
        allFiles.append(fullPath)
              
    return allFiles

In [ ]:
def Configure_CNN_Model(output_size):
    """This function defines the cnn model structure and configures the layers"""
    K.clear_session()
    model = Sequential()
    model.add(Dropout(0.4,input_shape=(224, 224, 3)))
    
    model.add(Conv2D(256, (5, 5),input_shape=(224, 224, 3),activation='relu'))
    model.add(MaxPool2D(pool_size=(2, 2)))
    #model.add(BatchNormalization())

    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPool2D(pool_size=(2, 2)))
    #model.add(BatchNormalization())

    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPool2D(pool_size=(2, 2)))
    #model.add(BatchNormalization())

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.3))
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(0.3))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.3))

    model.add(Dense(output_size, activation='softmax'))
    
    return model

In [ ]:
def PrepreocessData(subfolders):
    """Pre precess the image data in the provided category list"""
    X_data,Y_data,found = [],[],[]
    id_no=0
    #itering in all folders under Boats folder
    for paths in subfolders:
        #setting folder path for each boat type
        files = glob.glob (paths + "/*.jpg")
        found.append((paths.split('/')[-2],paths.split('/')[-1]))
        
        #itering all files under the folder one by one
        for myFile in files:
            img = Image.open(myFile)
            #img.thumbnail((width, height), Image.ANTIALIAS) # resizes image in-place keeps ratio
            img = img.resize((224,224), Image.ANTIALIAS) # resizes image without ratio
            #convert the images to numpy arrays
            img = np.array(img)
            if img.shape == ( 224, 224, 3):
                # Add the numpy image to matrix with all data
                X_data.append (img)
                Y_data.append (id_no)
        id_no+=1

    #converting lists to np arrays again
    X = np.array(X_data)
    Y = np.array(Y_data)

    # Print shapes to see if they are correct
    print("x-shape",X.shape,"y shape", Y.shape)

    X = X.astype('float32')/255.0
    y_Bird = to_categorical(Y_data, len(subfolders))

    print("X shape",X,"y_Bird shape", y_Bird)
    print("X shape",X.shape,"y_Bird shape", y_Bird.shape)

    return X_data,Y_data,X,y_Bird,found; 

In [ ]:
def splitData():
    X_train, X_test, y_train, y_test = train_test_split(X, y_Bird, test_size=0.2)
    print("The model has " + str(len(X_train)) + " inputs")
    return X_train, X_test, y_train, y_test

#The AugumentData.py will generate many images with the original dataset to increase the accuracy of the model.

In [ ]:
# Loading the augumented data form local storage
aug_data_location = "/content/drive/MyDrive/DigitalNaturalist/Augumented Dataset/Augumented Dataset" 
Folders = generateListofFiles(aug_data_location)
subfolders = []
for num in range(len(Folders)):
    sub_fols = generateListofFiles(Folders[num])
    subfolders+=sub_fols

X_data,Y_data,X,y_Bird,found= PrepreocessData(subfolders)
# Splitting the data to Test and Train
X_train, X_test, y_train, y_test = splitData()

x-shape (277, 224, 224, 3) y shape (277,)
X shape [[[[0.07058824 0.09019608 0.06666667]
   [0.0627451  0.08235294 0.05882353]
   [0.04313726 0.0627451  0.03921569]
   ...
   [0.03529412 0.04313726 0.03921569]
   [0.04313726 0.05098039 0.04705882]
   [0.04313726 0.05098039 0.04705882]]

  [[0.08235294 0.10196079 0.07843138]
   [0.07450981 0.09411765 0.07058824]
   [0.06666667 0.08627451 0.0627451 ]
   ...
   [0.03921569 0.04705882 0.04313726]
   [0.04313726 0.05098039 0.04705882]
   [0.04313726 0.05098039 0.04705882]]

  [[0.10196079 0.12156863 0.09803922]
   [0.10196079 0.12156863 0.09803922]
   [0.09803922 0.11764706 0.09411765]
   ...
   [0.03921569 0.04705882 0.04313726]
   [0.04705882 0.05490196 0.05098039]
   [0.04705882 0.05490196 0.05098039]]

  ...

  [[0.85490197 0.74509805 0.6745098 ]
   [0.8627451  0.75686276 0.69411767]
   [0.8117647  0.7176471  0.65882355]
   ...
   [0.43137255 0.5411765  0.47058824]
   [0.42745098 0.5372549  0.46666667]
   [0.41568628 0.5254902  0.4549019

#BUILDING THE CNN MODEL

In [ ]:
early_stop_loss = EarlyStopping(monitor='loss', patience=3, verbose=1)
early_stop_val_acc = EarlyStopping(monitor='val_accuracy', patience=3, verbose=1)
model_callbacks=[early_stop_loss, early_stop_val_acc]

In [ ]:
model = Configure_CNN_Model(6)
model.compile(loss='categorical_crossentropy',optimizer=Adam(lr=0.001),metrics=['accuracy'])
weights = model.get_weights()
model.set_weights(weights)

/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


#PREDECTING IMAGE CLASSES

In [ ]:
# random.randint(0,len(X_test))
# [X_test[image_number]

In [ ]:
image_number = random.randint(0,len(X_test))
predictions = model.predict([X_test[image_number].reshape(1, 224,224,3)])

for idx, result, x in zip(range(0,6), found, predictions[0]):
   print("Label: {}, Type : {}, Species : {} , Score : {}%".format(idx, result[0],result[1], round(x*100,3)))


#predicting the class with max probability
ClassIndex=np.argmax(model.predict([X_test[image_number].reshape(1, 224,224,3)]),axis=1)
print(found[ClassIndex[0]])

1/1 [==============================] - 0s 485ms/step
Label: 0, Type : Bird, Species : Great Indian Bustard Bird , Score : 15.794%
Label: 1, Type : Bird, Species : Spoon Billed Sandpiper Bird , Score : 18.182%
Label: 2, Type : Flower, Species : Corpse Flower , Score : 16.973%
Label: 3, Type : Flower, Species : Lady Slipper Orchid Flower , Score : 15.861%
Label: 4, Type : Mammal, Species : Pangolin Mammal , Score : 16.678%
Label: 5, Type : Mammal, Species : Senenca White Deer Mammal , Score : 16.512%
1/1 [==============================] - 0s 136ms/step
('Bird', 'Spoon Billed Sandpiper Bird')


#SAVING THE MODEL LOCALLY

In [ ]:
model_json = model.to_json() #indent=2
with open("DigitalNaturalist.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to H5

model.save_weights("DigitalNaturalist.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

--2022-11-15 08:23:44--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 52.202.168.65, 54.161.241.46, 54.237.133.81, ...
Connecting to bin.equinox.io (bin.equinox.io)|52.202.168.65|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13832437 (13M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip’

ngrok-stable-linux- 100%[===================>]  13.19M  54.8MB/s    in 0.2s    

2022-11-15 08:23:45 (54.8 MB/s) - ‘ngrok-stable-linux-amd64.zip’ saved [13832437/13832437]



In [ ]:
!unzip ngrok-stable-linux-amd64.zip

Archive:  ngrok-stable-linux-amd64.zip
  inflating: ngrok                   


In [ ]:
get_ipython().system_raw('./ngrok http 8501 &')

In [ ]:
!curl -s http://localhost:4040/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

Execute the next cell and the go to the following URL: http://8d54-35-245-103-185.ngrok.io


In [ ]:
!streamlit run /content/predict_image_class.py

/bin/bash: streamlit: command not found


#next method

In [ ]:
!unzip "/content/data.rar"

unzip:  cannot find or open /content/data.rar, /content/data.rar.zip or /content/data.rar.ZIP.


In [ ]:
import os, gc, glob, random
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import keras
from PIL import Image
from keras.layers import Dense,Flatten
from keras.models import Model
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split

In [ ]:
base_model = InceptionV3(input_shape=(224,224,3),include_top=False)

87910968/87910968 [==============================] - 1s 0us/step


In [ ]:
for layer in base_model.layers:
  layer.trainable = False

In [ ]:
X = Flatten()(base_model.output)

#using sigmoid function as activation funciton
X = Dense(units = 6, activation = 'sigmoid')(X)

In [ ]:
model = Model(base_model.input,X)

#using adam as the optimizer
#accuracy is set as the metrics to judge the performance of the model
model.compile(optimizer = 'adam',loss = keras.losses.binary_crossentropy,metrics=['accuracy'])

#summarizing the model
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d_3 (Conv2D)              (None, 111, 111, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 batch_normalization (BatchNorm  (None, 111, 111, 32  96         ['conv2d_3[0][0]']               
 alization)                     )                                                             

In [ ]:
#initializing the datagenerator
datagen = tf.keras.preprocessing.image.ImageDataGenerator()

#loading the train dataset from the directory
traindata= datagen.flow_from_directory(directory="/content/drive/MyDrive/DigitalNaturalist/Augumented Dataset/Augumented Dataset",target_size=(224,224),batch_size=100)

#loading the test dataset from the directory
testdata= datagen.flow_from_directory(directory="/content/drive/MyDrive/DigitalNaturalist/Augumented Dataset/Augumented Dataset",target_size=(224,224),batch_size=100)

Found 586 images belonging to 3 classes.
Found 586 images belonging to 3 classes.


In [ ]:
#listing the found classes from train dataset
traindata.class_indices

{'Bird': 0, 'Flower': 1, 'Mammal': 2}